services:
  db:
    image: postgres:15
    container_name: gym-postgres
    restart: always
    environment:
      POSTGRES_DB: gym_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    command: java -jar target/demo-0.0.1-SNAPSHOT.jar
    build: .
    container_name: gym-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gym_app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      APP_UPLOAD_DIR: /app/uploads
      APP_UPLOAD_BASE_URL: http://localhost:8080/api/images/exercises/
    volumes:
      - ./uploads:/app/uploads
    restart: always

volumes:
  postgres_data:
