version: "3.9"

services:
  db:
    image: postgres:15
    container_name: gym-postgres
    restart: always
    environment:
      POSTGRES_DB: gym_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1112
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: gym-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gym_app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1112
      JWT_SECRET: sua_chave_super_secreta
      GEMINI_API_KEY: sua_chave_gemini
      APP_UPLOAD_BASE_URL: https://seusite.com/api/uploads
    restart: always

volumes:
  postgres_data:
