version: "3.9"

services:
  db:
    image: postgres:15
    container_name: gym-postgres
    restart: always
    environment:
      POSTGRES_DB: gym_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1112
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: gym-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # Sobrescreve as configs do application.properties
      SPRING_PROFILES_ACTIVE: prod
      # Conecta no container 'db' e não em localhost
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gym_app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1112

      # SEGURANÇA
      JWT_SECRET: ${JWT_SECRET}
      GEMINI_API_KEY: ${GEMINI_API_KEY}

      # UPLOADS (Configuração Crítica)
      # Dentro do Docker, salvamos em /app/uploads
      APP_UPLOAD_DIR: /app/uploads
      # Para teste local via navegador
      APP_UPLOAD_BASE_URL: http://localhost:8080/api/images/exercises/
    volumes:
      # Mapeia a pasta 'uploads' do seu Windows para '/app/uploads' no Docker
      - ./uploads:/app/uploads
    restart: always

volumes:
  postgres_data: